version: '3.8'
services:

  bulletin_board:
    container_name: bulletin_board
    build: .
    command: >
      sh -c "python manage.py collectstatic --noinput
             python manage.py migrate
             gunicorn --workers 2 --timeout 1600 --bind 0.0.0.0:8000 core.wsgi --reload"
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - "./static:/app/static"
      - "./logs:/app/logs"
    depends_on:
        database:
          condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "2"

  database:
    image: mysql:8
    container_name: database
    restart: always
    env_file:
      - .env
    volumes:
      - "./database:/var/lib/mysql"
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SHOW DATABASES;'
      timeout: 30s
      interval: 15s
      retries: 3

  nginx:
    build: ./nginx
    volumes:
      - "./static_volume:/app/admin/static"
    ports:
      - "8031:80"
    depends_on:
      - bulletin_board
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "2"