# Generated by Django 4.2.5 on 2023-10-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board_app', '0002_alter_advert_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
